/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jp.visao;
import com.jp.modelos.Expressao;
import javax.swing.ImageIcon;

/**
 *
 * @author aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel1Apagar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResultado = new javax.swing.JLabel();
        jLabelApagar = new javax.swing.JLabel();
        jLabel1Apagar = new javax.swing.JLabel();
        jLabellinha = new javax.swing.JLabel();
        jLabelRaiz = new javax.swing.JLabel();
        jLabel1Raiz = new javax.swing.JLabel();
        jLabelPotencia = new javax.swing.JLabel();
        jLabel1Potencia = new javax.swing.JLabel();
        jLabelClear = new javax.swing.JLabel();
        jLabel1Clear = new javax.swing.JLabel();
        jLabelDivisao = new javax.swing.JLabel();
        jLabel1Divisao = new javax.swing.JLabel();
        jLabelVezes = new javax.swing.JLabel();
        jLabel1Vezes = new javax.swing.JLabel();
        jLabelMenos = new javax.swing.JLabel();
        jLabel1Menos = new javax.swing.JLabel();
        jLabelMais = new javax.swing.JLabel();
        jLabel1Mais = new javax.swing.JLabel();
        jLabelIgual = new javax.swing.JLabel();
        jLabel1Igual = new javax.swing.JLabel();
        jLabelVirgula = new javax.swing.JLabel();
        jLabel1Virgula = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MathBrain");
        setMinimumSize(new java.awt.Dimension(285, 485));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelResultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelResultado.setForeground(new java.awt.Color(51, 255, 255));
        jLabelResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelResultado.setText("0");
        getContentPane().add(jLabelResultado);
        jLabelResultado.setBounds(10, 30, 240, 60);

        jLabelApagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/delet 1.png"))); // NOI18N
        jLabelApagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelApagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelApagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelApagarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelApagarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelApagarMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelApagar);
        jLabelApagar.setBounds(210, 90, 50, 50);

        jLabel1Apagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Apagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Apagar);
        jLabel1Apagar.setBounds(210, 90, 50, 50);

        jLabellinha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabellinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/barrinha (5).png"))); // NOI18N
        getContentPane().add(jLabellinha);
        jLabellinha.setBounds(10, 130, 250, 20);

        jLabelRaiz.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelRaiz.setForeground(new java.awt.Color(51, 255, 255));
        jLabelRaiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRaiz.setText("√");
        jLabelRaiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRaizMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRaizMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRaizMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRaizMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelRaizMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelRaiz);
        jLabelRaiz.setBounds(140, 150, 50, 50);

        jLabel1Raiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Raiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Raiz);
        jLabel1Raiz.setBounds(140, 150, 50, 50);

        jLabelPotencia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPotencia.setForeground(new java.awt.Color(51, 255, 255));
        jLabelPotencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPotencia.setText("^");
        jLabelPotencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPotenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPotenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPotenciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelPotenciaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPotenciaMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelPotencia);
        jLabelPotencia.setBounds(80, 150, 50, 50);

        jLabel1Potencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Potencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Potencia);
        jLabel1Potencia.setBounds(80, 150, 50, 50);

        jLabelClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelClear.setForeground(new java.awt.Color(255, 75, 75));
        jLabelClear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelClear.setText("C");
        jLabelClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClearMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelClearMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelClear);
        jLabelClear.setBounds(20, 150, 50, 50);

        jLabel1Clear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Clear);
        jLabel1Clear.setBounds(20, 150, 50, 50);

        jLabelDivisao.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelDivisao.setForeground(new java.awt.Color(51, 255, 255));
        jLabelDivisao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDivisao.setText("÷");
        jLabelDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDivisaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDivisaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDivisaoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelDivisaoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelDivisaoMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelDivisao);
        jLabelDivisao.setBounds(200, 150, 50, 50);

        jLabel1Divisao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Divisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Divisao);
        jLabel1Divisao.setBounds(200, 150, 50, 50);

        jLabelVezes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelVezes.setForeground(new java.awt.Color(51, 255, 255));
        jLabelVezes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVezes.setText("×");
        jLabelVezes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVezesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelVezesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelVezesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelVezesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelVezesMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelVezes);
        jLabelVezes.setBounds(200, 210, 50, 50);

        jLabel1Vezes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Vezes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Vezes);
        jLabel1Vezes.setBounds(200, 210, 50, 50);

        jLabelMenos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMenos.setForeground(new java.awt.Color(51, 255, 255));
        jLabelMenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenos.setText("-");
        jLabelMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMenosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMenosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMenosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMenosMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelMenos);
        jLabelMenos.setBounds(200, 270, 50, 50);

        jLabel1Menos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Menos);
        jLabel1Menos.setBounds(200, 270, 50, 50);

        jLabelMais.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelMais.setForeground(new java.awt.Color(51, 255, 255));
        jLabelMais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMais.setText("+");
        jLabelMais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMaisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMaisMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMaisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMaisMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelMais);
        jLabelMais.setBounds(200, 330, 50, 50);

        jLabel1Mais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Mais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Mais);
        jLabel1Mais.setBounds(200, 330, 50, 50);

        jLabelIgual.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelIgual.setForeground(new java.awt.Color(51, 255, 255));
        jLabelIgual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIgual.setText("=");
        jLabelIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelIgualMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIgualMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIgualMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelIgualMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelIgualMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelIgual);
        jLabelIgual.setBounds(200, 390, 50, 50);

        jLabel1Igual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Igual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Igual);
        jLabel1Igual.setBounds(200, 390, 50, 50);

        jLabelVirgula.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelVirgula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVirgula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVirgula.setText(",");
        jLabelVirgula.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelVirgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVirgulaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelVirgulaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelVirgulaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelVirgulaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelVirgulaMouseReleased(evt);
            }
        });
        getContentPane().add(jLabelVirgula);
        jLabelVirgula.setBounds(140, 390, 50, 50);

        jLabel1Virgula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1Virgula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel1Virgula);
        jLabel1Virgula.setBounds(140, 390, 50, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("9");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 210, 50, 50);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(140, 210, 50, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 210, 50, 50);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(80, 210, 50, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 210, 50, 50);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 210, 50, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 270, 50, 50);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(140, 270, 50, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 270, 50, 50);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 270, 50, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 50, 50);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 270, 50, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 330, 50, 50);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(140, 330, 50, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 330, 50, 50);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 330, 50, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 330, 50, 50);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 330, 50, 50);

        jLabel0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel0.setForeground(new java.awt.Color(255, 255, 255));
        jLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel0.setText("0");
        jLabel0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel0MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel0);
        jLabel0.setBounds(80, 390, 50, 50);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 390, 50, 50);

        jLabelFundo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jp/imagens/fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 270, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel0MouseClicked

    private void jLabel0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseEntered
        // TODO add your handling code here:
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel0MouseEntered

    private void jLabel0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseExited
        // TODO add your handling code here:
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel0MouseExited

    private void jLabel0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MousePressed
        // TODO add your handling code here:
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel0MousePressed

    private void jLabel0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel0MouseReleased
        // TODO add your handling code here:
        jLabel10.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel0MouseReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        jLabel12.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        jLabel12.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        jLabel12.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        // TODO add your handling code here:
        jLabel12.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseReleased
        // TODO add your handling code here:
        jLabel13.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel3MouseReleased

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        jLabel14.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        jLabel14.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        jLabel14.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        // TODO add your handling code here:
        jLabel14.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        jLabel15.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        jLabel15.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        jLabel15.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        // TODO add your handling code here:
        jLabel15.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel16.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        jLabel16.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        jLabel16.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        // TODO add your handling code here:
        jLabel16.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel17.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        jLabel17.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        jLabel17.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        // TODO add your handling code here:
        jLabel17.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel7MouseReleased

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel18.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        jLabel18.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        jLabel18.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        // TODO add your handling code here:
        jLabel18.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        // TODO add your handling code here:
        jLabel19.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel9MouseReleased

    private void jLabelVirgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVirgulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelVirgulaMouseClicked

    private void jLabelVirgulaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVirgulaMouseEntered
        // TODO add your handling code here:
        jLabel1Virgula.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelVirgulaMouseEntered

    private void jLabelVirgulaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVirgulaMouseExited
        // TODO add your handling code here:
        jLabel1Virgula.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelVirgulaMouseExited

    private void jLabelVirgulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVirgulaMousePressed
        // TODO add your handling code here:
        jLabel1Virgula.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelVirgulaMousePressed

    private void jLabelVirgulaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVirgulaMouseReleased
        // TODO add your handling code here:
        jLabel1Virgula.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelVirgulaMouseReleased

    private void jLabelIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIgualMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelIgualMouseClicked

    private void jLabelIgualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIgualMouseEntered
        // TODO add your handling code here:
        jLabel1Igual.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelIgualMouseEntered

    private void jLabelIgualMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIgualMouseExited
        // TODO add your handling code here:
        jLabel1Igual.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelIgualMouseExited

    private void jLabelIgualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIgualMousePressed
        // TODO add your handling code here:
        jLabel1Igual.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelIgualMousePressed

    private void jLabelIgualMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIgualMouseReleased
        // TODO add your handling code here:
        jLabel1Igual.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelIgualMouseReleased

    private void jLabelMaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMaisMouseClicked

    private void jLabelMaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaisMouseEntered
        // TODO add your handling code here:
        jLabel1Mais.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelMaisMouseEntered

    private void jLabelMaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaisMouseExited
        // TODO add your handling code here:
        jLabel1Mais.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelMaisMouseExited

    private void jLabelMaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaisMousePressed
        // TODO add your handling code here:
        jLabel1Mais.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelMaisMousePressed

    private void jLabelMaisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMaisMouseReleased
        // TODO add your handling code here:
        jLabel1Mais.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelMaisMouseReleased

    private void jLabelMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMenosMouseClicked

    private void jLabelMenosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenosMouseEntered
        // TODO add your handling code here:
        jLabel1Menos.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelMenosMouseEntered

    private void jLabelMenosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenosMouseExited
        // TODO add your handling code here:
        jLabel1Menos.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelMenosMouseExited

    private void jLabelMenosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenosMousePressed
        // TODO add your handling code here:
        jLabel1Menos.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelMenosMousePressed

    private void jLabelMenosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenosMouseReleased
        // TODO add your handling code here:
        jLabel1Menos.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelMenosMouseReleased

    private void jLabelVezesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVezesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelVezesMouseClicked

    private void jLabelVezesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVezesMouseEntered
        // TODO add your handling code here:
        jLabel1Vezes.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelVezesMouseEntered

    private void jLabelVezesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVezesMouseExited
        // TODO add your handling code here:
        jLabel1Vezes.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelVezesMouseExited

    private void jLabelVezesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVezesMousePressed
        // TODO add your handling code here:
        jLabel1Vezes.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelVezesMousePressed

    private void jLabelVezesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVezesMouseReleased
        // TODO add your handling code here:
        jLabel1Vezes.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelVezesMouseReleased

    private void jLabelDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivisaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelDivisaoMouseClicked

    private void jLabelDivisaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivisaoMouseEntered
        // TODO add your handling code here:
        jLabel1Divisao.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelDivisaoMouseEntered

    private void jLabelDivisaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivisaoMouseExited
        // TODO add your handling code here:
        jLabel1Divisao.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelDivisaoMouseExited

    private void jLabelDivisaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivisaoMousePressed
        // TODO add your handling code here:
        jLabel1Divisao.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelDivisaoMousePressed

    private void jLabelDivisaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDivisaoMouseReleased
        // TODO add your handling code here:
        jLabel1Divisao.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelDivisaoMouseReleased

    private void jLabelClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelClearMouseClicked

    private void jLabelClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMouseEntered
        // TODO add your handling code here:
        jLabel1Clear.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelClearMouseEntered

    private void jLabelClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMouseExited
        // TODO add your handling code here:
        jLabel1Clear.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelClearMouseExited

    private void jLabelClearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMousePressed
        // TODO add your handling code here:
        jLabel1Clear.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelClearMousePressed

    private void jLabelClearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClearMouseReleased
        // TODO add your handling code here:
        jLabel1Clear.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelClearMouseReleased

    private void jLabelPotenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPotenciaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPotenciaMouseClicked

    private void jLabelPotenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPotenciaMouseEntered
        // TODO add your handling code here:
        jLabel1Potencia.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelPotenciaMouseEntered

    private void jLabelPotenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPotenciaMouseExited
        // TODO add your handling code here:
        jLabel1Potencia.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelPotenciaMouseExited

    private void jLabelPotenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPotenciaMousePressed
        // TODO add your handling code here:
        jLabel1Potencia.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelPotenciaMousePressed

    private void jLabelPotenciaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPotenciaMouseReleased
        // TODO add your handling code here:
        jLabel1Potencia.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelPotenciaMouseReleased

    private void jLabelRaizMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRaizMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelRaizMouseClicked

    private void jLabelRaizMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRaizMouseEntered
        // TODO add your handling code here:
        jLabel1Raiz.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelRaizMouseEntered

    private void jLabelRaizMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRaizMouseExited
        // TODO add your handling code here:
        jLabel1Raiz.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelRaizMouseExited

    private void jLabelRaizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRaizMousePressed
        // TODO add your handling code here:
        jLabel1Raiz.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelRaizMousePressed

    private void jLabelRaizMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRaizMouseReleased
        // TODO add your handling code here:
        jLabel1Raiz.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabelRaizMouseReleased

    private void jLabelApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApagarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelApagarMouseClicked

    private void jLabelApagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApagarMouseEntered
        // TODO add your handling code here:
        jLabel1Apagar.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
        jLabel1Apagar.setVisible(true);
    }//GEN-LAST:event_jLabelApagarMouseEntered

    private void jLabelApagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApagarMouseExited
        // TODO add your handling code here:
        jLabel1Apagar.setVisible(false);
    }//GEN-LAST:event_jLabelApagarMouseExited

    private void jLabelApagarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApagarMousePressed
        // TODO add your handling code here:
        jLabel1Apagar.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabelApagarMousePressed

    private void jLabelApagarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelApagarMouseReleased
        // TODO add your handling code here:
        jLabel1Apagar.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabelApagarMouseReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Normal.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/clique.png")));
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        // TODO add your handling code here:
        jLabel11.setIcon(new ImageIcon(getClass().getResource("/com/jp/imagens/Mouse.png")));
    }//GEN-LAST:event_jLabel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1Apagar;
    private javax.swing.JLabel jLabel1Clear;
    private javax.swing.JLabel jLabel1Divisao;
    private javax.swing.JLabel jLabel1Igual;
    private javax.swing.JLabel jLabel1Mais;
    private javax.swing.JLabel jLabel1Menos;
    private javax.swing.JLabel jLabel1Potencia;
    private javax.swing.JLabel jLabel1Raiz;
    private javax.swing.JLabel jLabel1Vezes;
    private javax.swing.JLabel jLabel1Virgula;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApagar;
    private javax.swing.JLabel jLabelClear;
    private javax.swing.JLabel jLabelDivisao;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelIgual;
    private javax.swing.JLabel jLabelMais;
    private javax.swing.JLabel jLabelMenos;
    private javax.swing.JLabel jLabelPotencia;
    private javax.swing.JLabel jLabelRaiz;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelVezes;
    private javax.swing.JLabel jLabelVirgula;
    private javax.swing.JLabel jLabellinha;
    // End of variables declaration//GEN-END:variables
}
